### ISSUE TITLE
Cuda out of memory error

### ISSUE THREAD

**Issue by AyushP123** [clovaai/CRAFT-pytorch#15]
Hi,
      I was trying to run the command 
`python test.py --trained_model=./craft_mlt_25k.pth --test_folder=./test_data` and got the error.

> RuntimeError: CUDA out of memory. Tried to allocate 100.00 MiB (GPU 0; 3.95 GiB total capacity; 2.88 GiB already allocated; 58.25 MiB free; 42.71 MiB cached)

There is no other process running on my laptop and I have a 4GB NVIDIA 1080 TI GPU.

**Comment by vjrai98** [comment]
reduce your image image size to 100 pixel width, i too was having this problem on nvidia mx150 2gb for image with bigger resolution and size, when i reduced it to 100 pixel width it worked.

**Comment by AyushP123** [comment]
I moved onto 24 GB Titan RTX and it worked, thanks for your response

**Comment by jussyr** [comment]
I realize I'm posting on an issue that was closed a month ago, but thought this might help others who come across it.  I had a similar issue, but was able to solve it by using "with torch.no_grad():" before the "# load data" loop in the test.py file.  That disables the gradient computation (and memory usage), which isn't needed for inference/deployment/evaluation.  Alternatively, I think you could place the "with torch.no_grad():" statement right before the forward pass in the test_net in test.py, and that would work as well.
